### PR TITLE
Address configure issues for unusual CC/CFLAGS

### PR DESCRIPTION
**Pull request by Algunenano**
I've been trying to run both postgres and postgis fully under the sanitizers and this blocked configure/compile steps.

### CODE REVIEW

**Comment by Algunenano** [comment]
Trac issue: https://trac.osgeo.org/postgis/ticket/3995

**Comment by Komzpa** [comment]
Hi,

Is it the reason why codecov is not showing any converage for raster?

**Comment by Algunenano** [comment]
Do you mean some specific part of raster? It seems like nothing changed with [my changes](https://codecov.io/gh/postgis/postgis/tree/8fce44923b9298c1fd487c8a34914bc932773892/raster)

**Comment by Komzpa** [comment]
@Algunenano looking at codecov, rt_pg is particularly red. Wasn't sure if it's due to absence of tests or due to issues with coverage calculation.

**Review by strk — COMMENTED** [review]
This commit broke build configurations using --without-pgconfig

**Pull request closed without merging**
