### PR TITLE
ST_AsMVT: Proper handling of id column

### PR DESCRIPTION
**Pull request by Algunenano**
Trac: https://trac.osgeo.org/postgis/ticket/4128

Missing documentation update

### CODE REVIEW

**Comment by Komzpa** [comment]
@Algunenano thanks for getting this polished! :)

**Comment by Algunenano** [comment]
Np, I've been looking into the MVT code lately so I knew where to look.

**Comment by joedjc** [comment]
@Algunenano This is great! It will be really useful in combination with the new feature-state mapbox feature. Do you have an idea when this will be available to use? I notice it's listed as part of the 3.0 release, but according to the roadmap that could be a year away? Would be great if it can make the next release if it's ready

**Comment by Komzpa** [comment]
@joedjc it will be around next september, PostGIS 2.5.0 just went out. You can use development builds for now.

**Comment by joedjc** [comment]
@Komzpa Thank you for the quick reply. Ok I will try that as it would be a shame not to be able to use this now. I've not used a dev build before so if you have any reference on how to use (and if it's possible to use with a AWS managed RDS) i'd be very grateful.

**Pull request closed without merging**
