### PR TITLE
Fix the unit test bug for #1051d, same as normalize_address_regress.

### PR DESCRIPTION
**Pull request by w345731923**
All 3 tests passed.

### CODE REVIEW

**Comment by strk** [comment]
Is there a trac ticket observing the bug being fixed here ? 
Please file one if not already existing, and reference from here.

https://trac.osgeo.org/postgis

**Comment by strk** [comment]
I guess this might refer to https://trac.osgeo.org/postgis/ticket/1051 which is marked as already fixed 13 years ago ?
@robe2 idea why no bot is catching this ?

**Comment by strk** [comment]
I've filed https://trac.osgeo.org/postgis/ticket/5813 for the missing catch by bots

**Comment by w345731923** [comment]
> 我想这可能指的是 [13](https://trac.osgeo.org/postgis/ticket/1051) 年前被标记为已经修复的 https://trac.osgeo.org/postgis/ticket/1051？ 知道为什么没有机器人捕获这个吗？

The CI likely doesn't validate postgis_tiger_geocoder and address_standardizer.

**Comment by strk** [comment]
Thanks, merged as 64239b716764c26f1c266e38569815f77dc3ae98

**Pull request closed without merging**
