### PR TITLE
Wkt enforce whitespace

### PR DESCRIPTION
**Pull request by Algunenano**
Fix for https://trac.osgeo.org/postgis/ticket/4109

It'd great if someone with experience with Bison could have a look.

### CODE REVIEW

**Comment by Komzpa** [comment]
If it does not break an existing test, I'd say we merge this.
(WKT input is also tested via oss-fuzz so a major crash, if any, will be found.)

**Comment by pramsey** [comment]
I find the solution breathtakingly ugly so I'm looking for a better way...

**Comment by Algunenano** [comment]
> I find the solution breathtakingly ugly so I'm looking for a better way...

I'm not going to disagree with you on this one. It is extremely ugly :japanese_ogre:

**Comment by pramsey** [comment]
I think the following two-liner is sufficient to fix the issue:
```
--?(([0-9]+\.?)|([0-9]*\.?[0-9]+)([eE][-+]?[0-9]+)?) {  
+-?(([0-9]+\.?)|([0-9]*\.?[0-9]+)([eE][-+]?[0-9]+)?)[ \,\)] {
       LWDEBUG(5,"DOUBLE");
       wkt_yylval.doublevalue = atof(wkt_yytext);
+      yyless(wkt_yyleng-1);
       return DOUBLE_TOK;
       }
```
The pattern change insists that all doubles must be anchored at the end by a space, comma or close bracket. The call to `yyless` puts that anchor back into the input stream so that it can subsequently be picked up by things like the comma and bracket patterns.

**Comment by Algunenano** [comment]
> The pattern change insists that all doubles must be anchored at the end by a space, comma or close bracket. The call to yyless puts that anchor back into the input stream so that it can subsequently be picked up by things like the comma and bracket patterns.

What about multiple spaces, tabs or CRs? I'll try to add them with a few tests

**Comment by pramsey** [comment]
I'm not sure how much more lenient we want to be WRT CRs. Tabs maybe. Multiples should end up being eaten by the whitespace rule at the bottom, so don't add them to the double pattern.

**Comment by Algunenano** [comment]
I've added single `\t` `\n` `\r`. This might still not be enough for Windows (`\r\n`); is it worth it to address it?

**Comment by pramsey** [comment]
I don't think so. If your WKT is
```
POINT(123.
4123)
```
you're SOL, sorry.

**Comment by pramsey** [comment]
👍

**Pull request closed without merging**
