### PR TITLE
using ExecutorStart_hook to reset interrupt flags

### PR DESCRIPTION
**Pull request by mngr777**
Fix for "interrupt handler called in wrong query" https://trac.osgeo.org/postgis/ticket/5137

Interrupt flags for Postgis, Wagyu and GEOS can be left set after query is executed, causing next query to be "interrupted".
PostgreSQL ExecutorStart hook allows to reset this flags before executing a query.

### CODE REVIEW

**Review by kalenikaliaksandr — APPROVED** [review]

**Comment by Komzpa** [comment]
add NEWS entry please

**Review by Komzpa — APPROVED** [review]

**Comment by robe2** [comment]
I'll rebase and merge in a bit.

**Comment by robe2** [comment]
I'm running into issues compiling this under mingw64.  I suspect it's just because mingw64 is sensitive about order of includes.

I get this error:
```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2   -shared -static-libgcc -o postgis-3.3.dll  postgis_module.o lwgeom_accum.o lwgeom_spheroid.o lwgeom_ogc.o lwgeom_functions_analytic.o lwgeom_inout.o lwgeom_functions_basic.o lwgeom_btree.o lwgeom_box.o lwgeom_box3d.o lwgeom_geos.o lwgeom_geos_prepared.o lwgeom_geos_clean.o lwgeom_geos_relatematch.o lwgeom_generate_grid.o lwgeom_export.o lwgeom_in_gml.o lwgeom_in_kml.o lwgeom_in_marc21.o lwgeom_out_marc21.o lwgeom_in_geohash.o lwgeom_in_geojson.o lwgeom_in_encoded_polyline.o lwgeom_triggers.o lwgeom_dump.o lwgeom_dumppoints.o lwgeom_functions_lrs.o lwgeom_functions_temporal.o lwgeom_rectree.o long_xact.o lwgeom_sqlmm.o lwgeom_rtree.o lwgeom_transform.o lwgeom_window.o gserialized_typmod.o gserialized_gist_2d.o gserialized_gist_nd.o gserialized_supportfn.o gserialized_spgist_2d.o gserialized_spgist_3d.o gserialized_spgist_nd.o brin_2d.o brin_nd.o brin_common.o gserialized_estimate.o geography_inout.o geography_btree.o geography_centroid.o geography_measurement.o geography_measurement_trees.o geometry_inout.o postgis_libprotobuf.o vector_tile.pb-c.o geobuf.pb-c.o mvt.o lwgeom_out_mvt.o geobuf.o lwgeom_out_geobuf.o lwgeom_out_geojson.o flatgeobuf.o lwgeom_in_flatgeobuf.o lwgeom_out_flatgeobuf.o postgis_legacy.o -Wl,--enable-auto-import -L/projects/postgresql/rel/pg15w64gcc81/lib  -L/projects/lz4/rel-lz4-1.9.3w64gcc81/bin  -L/projects/rel-libiconv-1.16w64gcc81/lib -L/projects/zlib/rel-zlib-1.2.11w64gcc81/lib -lm  ../deps/wagyu/libwagyu.la -lstdc++ ../deps/flatgeobuf/libflatgeobuf.la -lstdc++ ../libpgcommon/libpgcommon.a ../liblwgeom/.libs/liblwgeom.a  -L/projects/geos/rel-3.11w64gcc81/lib -lgeos_c -LC:/ming64gcc81/projects/proj/rel-7.2.1w64gcc81/lib -lproj   -LC:/ming64gcc81/projects/json-c/rel-0.12w64gcc81/lib -ljson-c   -LC:/ming64gcc81/projects/protobuf/rel-3.2.0w64gcc81/lib -lprotobuf-c   -L/projects/libxml/rel-libxml2-2.9.9w64gcc81/lib -lxml2 -liconv -lws2_32 -L/projects/CGAL/rel-sfcgal-1.4.1w64gcc81/lib -lSFCGAL -Wl,--exclude-libs,ALL -Wl,--enable-auto-import -L/projects/postgresql/rel/pg15w64gcc81/lib  -L/projects/lz4/rel-lz4-1.9.3w64gcc81/bin  -L/projects/rel-libiconv-1.16w64gcc81/lib -L/projects/zlib/rel-zlib-1.2.11w64gcc81/lib -lm -static-libstdc++ -lstdc++ -Wl,-Bdynamic -lm -LC:/MING64~1/projects/POSTGR~1/rel/PG15W6~2/lib -lpostgres -lpgcommon -lpgport -llz4 -lxml2 -lz -lws2_32 -lm  -lws2_32 -Wl,--export-all-symbols -Wl,--out-implib=libpostgis-3.3.a
postgis_module.o: In function `onExecutorStart':
C:\ming64gcc81\projects\postgis\postgis-git\postgis/postgis_module.c:128: undefined reference to `lwgeom_wagyu_interruptReset'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [C:/MING64~1/projects/POSTGR~1/rel/PG15W6~2/lib/pgxs/src/MAKEFI~1/../../src/Makefile.shlib:374: postgis-3.3.dll] Error 1
make[1]: Leaving directory '/projects/postgis/postgis-git/postgis'
make: *** [GNUmakefile:24: all] Error 1
```

**Comment by robe2** [comment]
I think I must have some compiled junk somewhere cause i can't see much of a difference between how the new function is called and old.  So I'll see if same issue happens on winnie and reopen it in that case.

**Pull request closed without merging**
