### PR TITLE
[WIP] Optimize varlena output functions

### PR DESCRIPTION
**Pull request by Algunenano**
Related to https://trac.osgeo.org/postgis/ticket/4623

The idea behind this PR is to enable liblwgeom to output an array that could be returned directly to Postgresql without any copies. I want to understand how invasive the changes are and what's the impact in performance.

This could potentially be used in multiple output functions such as `ST_AsGeoJSON` (first commit here), `ST_AsBinary`, `ST_AsText`...

### CODE REVIEW

**Comment by Algunenano** [comment]
Tested ST_AsText and the impact is basically nothing. I'm going to test ST_AsBinary and ST_AsTWKB just in case; ST_AsBinary at least it's faster, so the impact of not copying buffers should be more noticeable. If it isn't, I'll discard this completely.

**Comment by Komzpa** [comment]
why is codecov popping up? was the disable line lost from configs somehow?

**Comment by Algunenano** [comment]
I've tested (https://github.com/Algunenano/postgis/tree/varlena_wkb) an implementation of ST_AsBinary (and all associated functions) and it is 6-22% faster but I have introduced some bug at some point since I have some failures. It does look promising so I'll review everything with more calm to introduce a commit here with the changes.

**Comment by Algunenano** [comment]
Implemented over the WKB variants (there are multiple functions affected). Measurements:

```
-- 683788 Points (1 vertex on avg :D)ls
-- EXPLAIN ANALYZE Select ST_AsBinary(the_geom) from benchmark_7773a711c8441d4b494a51fd9feebeac7a9b9c734619398620293;
-- Before: 7.807002 tps
-- After: 8.635077 tps
-- Perf: 1.1060x

-- 489298 Lines (~5.7 vertices on avg)
-- EXPLAIN ANALYZE Select ST_AsBinary(the_geom) from benchmark_da625777246e392648f7d78b912233019d0cb2ffbf91acb187913;
-- Before: 7.621094 tps
-- After: 8.075582 tps
-- Perf: 1.0596x

-- 1083175 Small polygons (~9 vertices on avg)
-- EXPLAIN ANALYZE Select ST_AsBinary(the_geom) from benchmark_af85af967525e69373b7b8678f3bd409a8e78f447671344b7535d;
-- Before: 3.841667 tps
-- After: 4.216442 tps
-- Perf: 1.0975x

-- 13 big polygons (~260843 vertices on avg)
-- EXPLAIN ANALYZE Select ST_AsBinary(the_geom) from benchmark_4c7214d90a79aa6760367a084a4d4a2f61fbe1c6cc4f7f9e76020;
-- Before: 20.638837 tps
-- After: 24.819581 tps
-- Perf: 1.2025x
```

**Comment by Algunenano** [comment]
TWKB changed too. The improvements are marginal (1-3%):
```
-- 683788 Points (1 vertex on avg)
-- EXPLAIN ANALYZE Select ST_AsTWKB(the_geom) from benchmark_7773a711c8441d4b494a51fd9feebeac7a9b9c734619398620293;
-- Before: 7.094080 tps
-- After: 7.143945 tps
-- Perf: 1.0070x

-- 489298 Lines (~5.7 vertices on avg)
-- EXPLAIN ANALYZE Select ST_AsTWKB(the_geom) from benchmark_da625777246e392648f7d78b912233019d0cb2ffbf91acb187913;
-- Before: 6.783711 tps
-- After: 6.853756 tps
-- Perf: 1.0103x

-- 1083175 Small polygons (~9 vertices on avg)
-- EXPLAIN ANALYZE Select ST_AsTWKB(the_geom) from benchmark_af85af967525e69373b7b8678f3bd409a8e78f447671344b7535d;
-- Before: 3.495658 tps
-- After: 3.550130 tps
-- Perf: 1.0155x

-- 13 big polygons (~260843 vertices on avg)
EXPLAIN ANALYZE Select ST_AsTWKB(the_geom) from benchmark_4c7214d90a79aa6760367a084a4d4a2f61fbe1c6cc4f7f9e76020;
-- Before: 11.073627 tps
-- After: 11.379276 tps
-- Perf: 1.0276x
```

I'm going to review some pending output functions to see if they can also benefit from this kind of changes (I would expect so): KML, GML, SVG, X3D, GeoHash

**Comment by Algunenano** [comment]
Also a marginal improvement (1-2%) for ST_AsKML:
```
-- 683788 Points (1 vertex on avg)
EXPLAIN ANALYZE Select ST_AsKML(the_geom) from benchmark_7773a711c8441d4b494a51fd9feebeac7a9b9c734619398620293;
-- Before: 2.527324 tps
-- After: 2.544996 tps
-- Perf: 1.0069 x

-- 489298 Lines (~5.7 vertices on avg)
-- EXPLAIN ANALYZE Select ST_AsKML(the_geom) from benchmark_da625777246e392648f7d78b912233019d0cb2ffbf91acb187913;
-- Before: 0.707353 tps
-- After: 0.714354 tps
-- Perf: 1.0098 x

-- 1083175 Small polygons (~9 vertices on avg)
-- EXPLAIN ANALYZE Select ST_AsKML(the_geom) from benchmark_af85af967525e69373b7b8678f3bd409a8e78f447671344b7535d;
-- Before: 0.239224 tps
-- After: 0.241276 tps
-- Perf: 1.0085 x

-- 13 big polygons (~260843 vertices on avg)
-- EXPLAIN ANALYZE Select ST_AsKML(the_geom) from benchmark_4c7214d90a79aa6760367a084a4d4a2f61fbe1c6cc4f7f9e76020;
-- Before: 0.178417 tps
-- After: 0.181457 tps
-- Perf: 1.0170 x
```

**Comment by Algunenano** [comment]
Implemented for GeoHash, ~10% improvements for points (I haven't tested other cases, since I don't think are significative):
```
-- 683788 Points (1 vertex on avg)
EXPLAIN ANALYZE Select ST_GeoHash(the_geom) from benchmark_7773a711c8441d4b494a51fd9feebeac7a9b9c734619398620293;
-- Before: 4.855698 tps
-- After: 5.299335 tps
-- Perf: 1.091 x
```

**Comment by Algunenano** [comment]
I think that now covers every important output function. I'll do some final benchmarks and merge unless anybody complains.

**Comment by Algunenano** [comment]
X3D: ~3% improvement
```
-- 683788 Points (1 vertex on avg)
EXPLAIN ANALYZE Select ST_AsX3D(the_geom) from benchmark_7773a711c8441d4b494a51fd9feebeac7a9b9c734619398620293;
-- Before: 0.025865 tps
-- After: 0.026718 tps
-- Perf: 1.0329x

-- 489298 Lines (~5.7 vertices on avg)
-- EXPLAIN ANALYZE Select ST_AsX3D(the_geom) from benchmark_da625777246e392648f7d78b912233019d0cb2ffbf91acb187913;
-- Before: 0.033178 tps
-- After: 0.034265 tps
-- Perf: 1.0327 x

-- 1083175 Small polygons (~9 vertices on avg)
-- EXPLAIN ANALYZE Select ST_AsX3D(the_geom) from benchmark_af85af967525e69373b7b8678f3bd409a8e78f447671344b7535d;
-- Before: 0.014596 tps
-- After: 0.015085 tps
-- Perf:  1.0335x

-- 13 big polygons (~260843 vertices on avg)
-- EXPLAIN ANALYZE Select ST_AsX3D(the_geom) from benchmark_4c7214d90a79aa6760367a084a4d4a2f61fbe1c6cc4f7f9e76020;
-- Before: 0.713027 tps
-- After: 0.738587 tps
-- Perf: 1.0358x
```

ST_AsGML: 0 to 7% improvement
```
-- 683788 Points (1 vertex on avg)
EXPLAIN ANALYZE Select ST_AsGML(the_geom) from benchmark_7773a711c8441d4b494a51fd9feebeac7a9b9c734619398620293;
-- Before: 0.119722 tps
-- After: 0.120075 tps
-- Perf: 1.0029 x

-- 489298 Lines (~5.7 vertices on avg)
-- EXPLAIN ANALYZE Select ST_AsGML(the_geom) from benchmark_da625777246e392648f7d78b912233019d0cb2ffbf91acb187913;
-- Before: 0.124858 tps
-- After: 0.126692 tps
-- Perf: 1.0146 x

-- 1083175 Small polygons (~9 vertices on avg)
-- EXPLAIN ANALYZE Select ST_AsGML(the_geom) from benchmark_af85af967525e69373b7b8678f3bd409a8e78f447671344b7535d;
-- Before: 0.069138 tps
-- After: 0.069964 tps
-- Perf: 1.0119 x

-- 13 big polygons (~260843 vertices on avg)
-- EXPLAIN ANALYZE Select ST_AsGML(the_geom) from benchmark_4c7214d90a79aa6760367a084a4d4a2f61fbe1c6cc4f7f9e76020;
-- Before: 0.813557 tps
-- After: 0.872248 tps
-- Perf: 1.0721 x
```

ST_AsSVG: 3 to 7% improvement:
```
-- 683788 Points (1 vertex on avg)
EXPLAIN ANALYZE Select ST_AsSVG(the_geom) from benchmark_7773a711c8441d4b494a51fd9feebeac7a9b9c734619398620293;
-- Before: 5.940995 tps
-- After: 6.125753 tps
-- Perf: 1.03109 x

-- 489298 Lines (~5.7 vertices on avg)
-- EXPLAIN ANALYZE Select ST_AsSVG(the_geom) from benchmark_da625777246e392648f7d78b912233019d0cb2ffbf91acb187913;
-- Before: 2.828125 tps
-- After: 2.916545 tps
-- Perf: 1.0312 x

-- 1083175 Small polygons (~9 vertices on avg)
-- EXPLAIN ANALYZE Select ST_AsSVG(the_geom) from benchmark_af85af967525e69373b7b8678f3bd409a8e78f447671344b7535d;
-- Before: 1.287415 tps
-- After: 1.326895 tps
-- Perf: 1.0306 x

-- 13 big polygons (~260843 vertices on avg)
-- EXPLAIN ANALYZE Select ST_AsSVG(the_geom) from benchmark_4c7214d90a79aa6760367a084a4d4a2f61fbe1c6cc4f7f9e76020;
-- Before: 0.932382 tps
-- After: 0.992763 tps
-- Perf: 1.0647 x
```

ST_AsEncodedPolyline: ~3% improvement
```
-- 489298 Lines (~5.7 vertices on avg)
EXPLAIN ANALYZE Select ST_AsEncodedPolyline(ST_LineMerge(the_geom)) from benchmark_da625777246e392648f7d78b912233019d0cb2ffbf91acb187913;
-- Before: 1.640634 tps
-- After: 1.692809 tps
-- Perf: 1.0318 x
```

**Pull request closed without merging**
