### PR TITLE
Quote spatialRefSysSchema

### PR DESCRIPTION
**Pull request by Algunenano**
Fix for https://trac.osgeo.org/postgis/ticket/4661

### CODE REVIEW

**Comment by Komzpa** [comment]
up next: schema with quotes in it!

**Comment by Algunenano** [comment]
You are right. I'll search in the Postgresql code base to see if they have a C function to properly quote a name.

**Comment by Algunenano** [comment]
Ok, fixed completely for this case, you can go as crazy as you want

```
You are now connected to database "schema3" as user "postgres".
schema3=# create schema "schema-with-hypen spaces and """;
CREATE SCHEMA
schema3=# select schema_name from information_schema.schemata;
          schema_name           
--------------------------------
 pg_toast
 pg_temp_1
 pg_toast_temp_1
 pg_catalog
 public
 information_schema
 schema-with-hypen spaces and "
(7 rows)

schema3=# create extension postgis with schema "schema-with-hypen spaces and """;
CREATE EXTENSION
schema3=# select "schema-with-hypen spaces and """.ST_Distance('POINT (0 0)'::"schema-with-hypen spaces and """.geography, 'POINT (0 0)'::"schema-with-hypen spaces and """.geography);
 st_distance 
-------------
           0
(1 row)
```

I still need to review and fix any other internal usages via SPI_execute, at least the ones in lwgeom_export.c and maybe the ones under raster (not very happy about it).

**Comment by Algunenano** [comment]
GML currently fails for PROJ before 6 because it's using GetProjStringsSPI without calling postgis_initialize_cache, what before was SetSpatialRefSysSchema. So that's another bug uncovered :upside_down_face: 

I'll try to fix it tomorrow.

**Pull request closed without merging**
