### PR TITLE
Add IRC badge

### PR DESCRIPTION
**Pull request by strk**
Just an idea, mostly in response to recent @mloskot mediated (unintended) advertisement of a proprietary chat service :)

### CODE REVIEW

**Comment by mloskot** [comment]
:+1:

**Comment by strk** [comment]
Would be even better to drop the "kiwiirc.com" hosted client dependency, see https://trac.osgeo.org/osgeo/ticket/1639

(I guess I could just change the link to use `irc://` schema but I suspect most users going to Slack or Gitter won't have the browser correctly configured for that - correct me if I'm wrong)

**Comment by mloskot** [comment]
I think most IRC users are tech savvy enough to get the `irc://` working. Those who are not, they may go to Gitter.

**Comment by strk** [comment]
Pushed as r15024 = 307414769559ca936ed20f6af5b5d2c51455d88d (refs/remotes/trunk)

**Pull request closed without merging**
