### PR TITLE
Proj Utilities for Accessing Metadata

### PR DESCRIPTION
**Pull request by pramsey**

### CODE REVIEW

**Comment by robe2** [comment]
What's this for params->celestial_body_name = "Earth" .  Does that mean only Earth is supported?

**Comment by pramsey** [comment]
Yes, I did not bother to expose that knob.

**Comment by robe2** [comment]
> Yes, I did not bother to expose that knob.

I see so no Mars or Venus for now? What will I tell my people.

**Comment by pramsey** [comment]
When the colonization starts, we can revisit.

**Comment by robe2** [comment]
@pramsey are you waiting on something to commit this.  Hurry up before @strk has an idea.

**Pull request closed without merging**
