### PR TITLE
rtpg_wkb: Add missing include

### PR DESCRIPTION
**Pull request by Algunenano**

### CODE REVIEW

**Comment by Komzpa** [comment]
is that for https://trac.osgeo.org/postgis/ticket/4021 ? :)

**Comment by Algunenano** [comment]
Yes, it was introduced in https://trac.osgeo.org/postgis/ticket/2221 and I'm just waiting for the test to pass.

**Comment by Komzpa** [comment]
Thanks! CI passed, patch committed :)

**Comment by dustymugs** [comment]
How odd. Nothing about rtpg_wkb.c requires lwgeom...

**Comment by Algunenano** [comment]
`RASTER_fromHexWKB` uses `text2cstring`.

**Comment by dustymugs** [comment]
Yep. I see that. That wasn't intended. Should have been using text_to_cstring instead.

**Comment by pramsey** [comment]
There's no particular reason we couldn't strip out our implementation. I cannot recall if I put it in because there was no text_to_cstring at the time, or because I just didn't find it in the pgsql code base.

**Comment by Algunenano** [comment]
> There's no particular reason we couldn't strip out our implementation. I cannot recall if I put it in because there was no text_to_cstring at the time, or because I just didn't find it in the pgsql code base.

I've made a quick test and found there is at least issues with `lwgeom_in_geojson.c` as both Postgres `utils/builtins.h` and LibJSON `json-c/json.h` declare ```json_object```.

**Pull request closed without merging**
