### PR TITLE
Add projection 54009 / World Molleweide

### PR DESCRIPTION
**Pull request by Komzpa**
https://trac.osgeo.org/postgis/ticket/4417

### CODE REVIEW

**Comment by pramsey** [comment]
Is there a way to add this upstream to proj?

**Comment by rouault** [comment]
It is already in PROJ 6
```
$ src/projinfo ESRI:54009
PROJ.4 string:
+proj=moll +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +type=crs

WKT2_2018 string:
PROJCRS["World_Mollweide",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["Degree",0.0174532925199433]]],
    CONVERSION["World_Mollweide",
        METHOD["Mollweide"],
        PARAMETER["Longitude of natural origin",0,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["unknown"],
        AREA["World"],
        BBOX[-90,-180,90,180]],
    ID["ESRI",54009]]
```

**Comment by rouault** [comment]
See https://github.com/postgis/postgis/pull/438 that adds *all* ESRI definitions

**Comment by Komzpa** [comment]
Closing in favour of #438

**Pull request closed without merging**
