### PR TITLE
Upgrade FlatGeobuf to 3.25.0 (flatbuffers 23.3.3)

### PR DESCRIPTION
**Pull request by bjornharrtell**
Looks like this is failing build on some combinations but is a pre-existing issue.. that started only very recently (considering https://github.com/postgis/postgis/commit/a0d837334f7651905719d9308011c8e518bc55b6 passed four days ago).

Known issue is ticketed at https://trac.osgeo.org/postgis/ticket/5368.

### CODE REVIEW

**Comment by robe2** [comment]
I took out the cirrus 12.3 run, and upgraded bessie's freebsd to same patch level as what cirrus freebsd 12.3 was at.

The good news is she's not failing on flatgeobuf stuff running so I think the flatgeobuf is some pecularity with the cirrus 12.3 setup (the 13.1 setup seems fine).

The bad news is  bessie is failing on raster with new GDAL upgrade
https://debbie.postgis.net/view/PostGIS/job/PostGIS_Worker_Run/4437/label=bessie/console

```
20:26:02  -------------- Dependencies -------------- 
20:26:02   GEOS config:          /usr/local/bin/geos-config
20:26:02   GEOS version:         3.11.1
20:26:02   GDAL config:          /usr/local/bin/gdal-config
20:26:02   GDAL version:         3.6.2
20:26:02   SFCGAL config:        /usr/local/bin/sfcgal-config
20:26:02   SFCGAL version:       1.4.1
20:26:02   PostgreSQL config:    /usr/local/bin/pg_config
20:26:02   PostgreSQL version:   PostgreSQL 13.10
20:26:02   PROJ4 version:        92
20:26:02   Libxml2 config:       /usr/local/bin/xml2-config
20:26:02   Libxml2 version:      2.10.3
20:26:02   JSON-C support:       yes
20:26:02   protobuf support:     yes
20:26:02   protobuf-c version:   1004001
20:26:02   PCRE support:         Version 2
20:26:02   Perl:                 /usr/local/bin/perl
```


But that seems all unrelated to flatgeobuf and probably more to do with proj and gdal upgrade combo

**Comment by robe2** [comment]
@bjornharrtell  I think this is okay to committ.  Passes on my mingw64 setup with PG16.  The latest error is just the GDAL which is fixed in master.  You might want to rebase, just to confirm latest/coverage is fine, but I think it should be now the GDAL polygonize test has been fixed to accommodate GDAL 3.7

**Comment by bjornharrtell** [comment]
@robe2 rebased

**Comment by robe2** [comment]
> @robe2 rebased

Looks good.  I'd go ahead and commit

**Review by robe2 — APPROVED** [review]

**Comment by robe2** [comment]
@bjornharrtell  Let me know if you need help committing this.

**Comment by bjornharrtell** [comment]
Merged by https://git.osgeo.org/gitea/postgis/postgis/pulls/122.

**Pull request closed without merging**
