### PR TITLE
Convert GeoJSON output to use stringbuffer

### PR DESCRIPTION
**Pull request by pramsey**
Instead of count-n-fill procedure. Much less code, have not measured performance.

### CODE REVIEW

**Comment by robe2** [comment]
what's left to do here?  Just performance tests?

**Comment by pramsey** [comment]
Yeah, I fear it'll end up slower. Haven't tested yet.

**Comment by pramsey** [comment]
Mixed performance results. New code seems about 10% faster on a "small object" case, converting a large number of points, or a large number of two-point lines. New code seems about 5% slower on a "large object" case, converting the naturalearth admin layer. Not sure where that leaves us in terms of whether we want the change or not.

**Comment by pramsey** [comment]
Even after change, the timings above still hold.

**Pull request closed without merging**
