### PR TITLE
Upgrade path for address_standardizier_data_us and fix for upgrades as non-superuser via pgextwlist

### PR DESCRIPTION
**Pull request by jankatins**
* address_standardizier_data_us: provide upgrade path scripts: for address standardizer_data_us so this extension can be upgraded and does not need to be dropped/recreated
* Convert _postgis_upgrade_info to a function -> we use pgextwlist and that sets a security context which prevents creating temporary tables (see e.g. https://github.com/dimitri/pgextwlist/issues/43)

### CODE REVIEW

**Comment by robe2** [comment]
I haven't had a chance to look at this.  I'll take a look this weekend.

**Comment by robe2** [comment]
Related tickets:

https://trac.osgeo.org/postgis/ticket/4974

I thought I had  a ticket already for the _postgis_upgrade_info as that was a complaint of an Amazon RDS user too.  But they worked around the issue, so maybe I didn't bother putting in a ticket for it before. Related one:

https://trac.osgeo.org/postgis/ticket/4975

**Comment by jankatins** [comment]
for completeness: 
* I think this is the RDS problem you mention (on the mailinglist): https://www.mail-archive.com/postgis-users@lists.osgeo.org/msg08353.html
* Heroku also seems to have run into this error: https://stackoverflow.com/questions/54213361/update-postgis-extensions-on-heroku + https://trac.osgeo.org/postgis/ticket/4186 mention this error message

**Comment by robe2** [comment]
> 
> 
> for completeness:
> 
>     * I think this is the RDS problem you mention (on the mailinglist): https://www.mail-archive.com/postgis-users@lists.osgeo.org/msg08353.html
> 
>     * Heroku also seems to have run into this error: https://stackoverflow.com/questions/54213361/update-postgis-extensions-on-heroku + https://trac.osgeo.org/postgis/ticket/4186 mention this error message

More completeness:

https://lists.osgeo.org/pipermail/postgis-users/2020-May/044225.html

**Pull request closed without merging**
