### PR TITLE
WIP: CMake build configuration for PostGIS

### PR DESCRIPTION
**Pull request by mloskot**
Purpose of this pull request is to collect and **present all commits** related to CMake build configuration (plus, some Visual C++ fixes). The pull request is being frequently updated with new commits.

**IMPORTANT**: I don't expect to have this pull request accepted and changes committed into the PostGIS upstream in the Git repo I forked. This is only for communication purpose, to make it easy to visualise what has changed, and discuss it on postgis-devel mailing list (see [CMake Progress](http://postgis.refractions.net/pipermail/postgis-devel/2012-June/021091.html) thread)

The CMake config development started during [PostGIS Code Spring in Paris](http://trac.osgeo.org/postgis/wiki/CodeSprintParis2012).

### CODE REVIEW

**Comment by robe2** [comment]
I think this supercedes the above
https://gitlab.com/postgis/postgis/merge_requests/2

**Comment by Komzpa** [comment]
@mloskot hey! This PR requires a merge with trunk. Can you please make it and make sure that CI is green?

**Comment by mloskot** [comment]
@Komzpa 
>  This PR requires a merge with trunk

You rather mean to ask to rebase `mloskot:cmake-build` branch on top of the current trunk, no?

The CMake build is a prototype, needs work and, AFAIK, there is plan to merge CMake build into PostGIS upstream yet.

**Comment by Komzpa** [comment]
@mloskot I don't feel like there's a plan for anything. If it gets coded, it gets merged.  :)
Yes, a rebase, or a merge of trunk into mloskot:cmake-build, which are the same except for history..

**Comment by mloskot** [comment]
@Komzpa I should have say rather 'demand' for CMake. The core devs do not seem eager to use/maintain/switch to CMake themselves, so the steam run out. Feel free to push the project forward.

**Comment by Komzpa** [comment]
@mloskot if this isn't going to get merged, maybe it's better to close it, so that list isn't cluttered.

**Comment by strk** [comment]
a WIP label may be enough to avoid the clutter
anyway, if anyway wants to take care of maintaining
the github mirror please speakup on the mailing list
to get more powers to do these kind of things

**Pull request closed without merging**
