### PR TITLE
Converting from geocentric bounds to lonlat bounds

### PR DESCRIPTION
**Pull request by pramsey**
Added gbox_geocentric_get_gbox_cartesian to lwgeodetic.h

### CODE REVIEW

**Comment by robe2** [comment]
@coderabbitai comment

**Comment by strk** [comment]
I'm trying to hook your new code to the extent estimator and I'm getting these numbers, for a table with a single geography being at 10,10:

WARNING:  GBOX before: 0.969846 0.17101, 0.969846 0.17101
WARNING:  GBOX after: 10 -7.27973e-07, 10 7.27973e-07

I can't get my head around those numbers but they surely don't look right

**Comment by pramsey** [comment]
> I'm trying to hook your new code to the extent estimator and I'm getting these numbers, for a table with a single geography being at 10,10:
> 
> WARNING: GBOX before: 0.969846 0.17101, 0.969846 0.17101 

This looks correct for a geodetic volume around 10,10, but with one dimension missing in the printout. 

> WARNING: GBOX after: 10 -7.27973e-07, 10 7.27973e-07

This looks close to (10 0, 10 0), so "sort of, but not".

> I can't get my head around those numbers but they surely don't look right

**Comment by pramsey** [comment]
We don't put Z in the 2D histogram (assuming this is falling back to stats). But we do put it in the ND histogram. And we cannot ignore Z, we need it to form a useful geocentric bounding volume.

**Comment by robe2** [comment]
@pramsey cough cough, any plans to commit this like before release?

**Comment by robe2** [comment]
> @pramsey cough cough, any plans to commit this like before release?

cough cough cough cough - are you going to let this sit here forever?

**Comment by pramsey** [comment]
Already integrated, closing

**Pull request closed without merging**
