### PR TITLE
Explain units for DBSCAN

### PR DESCRIPTION
**Pull request by Komzpa**
Per request in IRC

### CODE REVIEW

**Comment by dbaston** [comment]
It seems confusing to link to `ST_Distance` which is not used for distance calculations here.

**Comment by Komzpa** [comment]
@dbaston do we have any better spot to link to, to explain what the units are? (without writing "units are map units" everywhere)

**Comment by dbaston** [comment]
What do you think about the note on `ST_ClusterWithin` ?

**Comment by robe2** [comment]
Are you guys ready to commit this so we can close this pull request?

**Pull request closed without merging**
