### PR TITLE
Impose minimum number of segments per arc during linearization

### PR DESCRIPTION
**Pull request by dbaston**
This PR implements fixed limits of 2 segments per non-circular arc and 3 segments per circular arc, following the discussion in [Trac #3719](https://trac.osgeo.org/postgis/ticket/3719).

The only logical changes are in 548fd5dd0c0; the preceding commits attempt to clarify some code but do not change any logic.

### CODE REVIEW

**Comment by Komzpa** [comment]
@dbaston how about getting this merged?

**Comment by dbaston** [comment]
@Komzpa I'd like to give the make sure the ticket author has an opportunity to check it out. Is there a hurry?

**Comment by Komzpa** [comment]
Hi,

6 days ago the original ticket author had no way to know about this PR. Pinging things to get them moving on github is my duty :)

It passes tests, passes coverage, and if it's covering the issues mentioned by ticket author - I'd say we just merge it and close ticket. If there are some more issues, that would deserve a new ticket.

If you're planning to backport it, 2.5.1 is in a few weeks according to @robe2's email.

**Comment by dbaston** [comment]
I don't plan to backport it because it's a behavior change. I'll merge it when I'm ready to merge it.

**Comment by giohappy** [comment]
@dbaston we can proceed with merge

**Comment by dbaston** [comment]
@strk @robe2 @pramsey  Do you have any thoughts about backporting the changes included in this PR to 2.5.x? On the one hand, they include a behavior change -- I had to change several test results -- but on the other hand, they fix a reported bug, and it's hard to imagine a case where the older behavior (linearizing an arc with a single straight line) is desirable.

**Comment by pramsey** [comment]
2.5 is relatively recent, so I'd feel OK about slightly bending the "no changes in behaviour" rule for this case.

**Comment by strk** [comment]
I'm ok with backporting. We can call it a bug.
Just make sure documentation didn't mention the straight line being 
a valid result !

**Pull request closed without merging**
