### PR TITLE
[cirrus-ci] use sudo

### PR DESCRIPTION
**Pull request by strk**
Trying to avoid a timeout

### CODE REVIEW

**Comment by lbartoletti** [comment]
You could up the timeout delay with:

```
task: 
  timeout_in: 90m
  ...
```

**Comment by strk** [comment]
The thing is that it should not take 1h to `createdb`, that's what we need to find the cause of

**Comment by strk** [comment]
See https://cirrus-ci.com/task/6474763102060544 -- 55 minutes waiting here:
```
sudo -u postgres createuser -s `whoami`
Shell session I/O error: context deadline exceeded
```

**Comment by strk** [comment]
It looks like CI is green now, so I guess nothing is needed anymore here

**Pull request closed without merging**
