### PR TITLE
Trac #3437, ST_Intersects incorrect for MultiPoints

### PR DESCRIPTION
**Pull request by dbaston**
https://trac.osgeo.org/postgis/ticket/3437

### CODE REVIEW

**Comment by dbaston** [comment]
Interim (or final?) fix applied to trunk at r14686, 2.2 at r14687

**Comment by strk** [comment]
I'd leave a POSTGIS_GEOS_VERSION macro, we know 3.6.0 will work.

**Comment by dbaston** [comment]
Do we know that it's faster though?

**Comment by strk** [comment]
Not w/out testing but if the comments and commit log refer
to a bug in GEOS it is useful to have immediate info about
which version of GEOS fixes that.

Then, if it's choosen not to use the prepared version for
points (or maybe small multipoints), it can still be done,
but not documenting the choice as driven by a bug...

**Pull request closed without merging**
