### PR TITLE
Fix issue with skipped tests not being cleaned up properly

### PR DESCRIPTION
**Pull request by maurizi**
This was what was causing the untracked file I noticed in #32.

### CODE REVIEW

**Comment by strk** [comment]
but, why was the test skipped ? Reading the code it looks like the skip is due to a missing file. Why is there a "pre" without a corresponding file ? There might be another bug hiding here

**Comment by dustymugs** [comment]
Having the *-post.pl run regardless of the test succeeding makes sense. The test itself isn't being skipped (as far as the latest trunk indicates). The *-pre generates the appropriate opt file and the *-post destroys it.

**Comment by maurizi** [comment]
@strk I think you're right, there is some underlying bug if the `BasicOutDb` test is being skipped.  Perhaps it is something specific to my environment that is causing the test to be skipped.

That said, it seems like a good practice to always run the *-post.pl if we run the corresponding *-pre.pl, regardless of whether the actual test is run or not.

**Comment by strk** [comment]
if we figure out what triggers the skip, it would probably make sense to skip the test completely, not running the *-pre.pl either.

**Comment by pramsey** [comment]
Thanks, applied, https://trac.osgeo.org/postgis/changeset/14679/

**Pull request closed without merging**
