### PR TITLE
Migrate Travis CI builds to container-based architecture

### PR DESCRIPTION
**Pull request by mloskot**
The `.travis.yml` update is sound.

## Status
Build is failing at the `installcheck` step due to issue:
* build generates `postgis-2.2`
* installcheck loads `postgis-2.1`
```
ERROR:  could not access file "$libdir/postgis-2.1": No such file or directory
```
* See detailed log at https://travis-ci.org/mloskot/postgis/builds/74320589

## Problem
[Pre-installed PostGIS](http://docs.travis-ci.com/user/using-postgresql/#Using-PostGIS) version conflicts with the build:
> All available versions of PostgreSQL come with PostGIS 2.1 packages preinstalled.

## Solution
* Install PostgreSQL from sources into `--prefix=$HOME/postgresql`, which does not require `sudo`.
* Alternatively, it may be possible to use sudo as per this message from the top of the build log:
> If you require sudo, add 'sudo: required' to your .travis.yml
> See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.

However, `sudo: required` means switch back to old non-container architecture.

### CODE REVIEW

**Comment by strk** [comment]
The problem is basically with testing EXTENSION (that's what installcheck does).
Extensions need to be installed on the PostgreSQL extension dir.
Since container-based travis architecture does not allow us to write in there (does it?) we cannot install.
I'm not sure why the "sudo make install" step did not fail though...

**Comment by mloskot** [comment]
@strk according to the [build 1 log](https://travis-ci.org/mloskot/postgis/builds/74320589) it failed:
```
The command "make check" exited with 0.
$ sudo make install
sudo: must be setuid root
The command "sudo make install" exited with 1.
```

**Comment by strk** [comment]
Ok, great.
But it didn't interrupt the build ?
Can it be made fatal, to reduce noise ?

**Comment by mloskot** [comment]
6 sie 2015 17:57 "Sandro Santilli" <notifications@github.com> napisał(a):
>
> But it didn't interrupt the build ?

"When one of the build commands returns a non-zero exit code, the Travis CI
build runs the subsequent commands as well, and accumulates the build
result."
http://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step

> Can it be made fatal, to reduce noise ?

Yes. Move all the `script` commands into shell script and check return
codes at each step, then report single code from the script as the build
status.

**Comment by strk** [comment]
@molskot I've recently used container-based builds on gitlab-ci, and found out you don't need sudo because you're already root in there ! Maybe it is the same here, did you try just removing the sudo usage ? (and an whoami call among the steps would help too...).

Seen the poor man's waterfall display, btw ? :)
https://trac.osgeo.org/postgis/

**Comment by pramsey** [comment]
@mloskot, @strk, is this still ongoing, or superceded?

**Comment by strk** [comment]
I'm not moving any step here. This wasn't merged because failing.

**Comment by pramsey** [comment]
If it's not going anywhere, close it out.

**Comment by strk** [comment]
Up to @mloskot, it's his PR ...

**Comment by mloskot** [comment]
Since the new container-based builders require no use of `sudo` whereas, AFAIK, we require it here, then I see no solution. Building PostgreSQL from sources makes little sense: it increases maintenance complexity and build startup performance gain would be cleared by the extended build time.

**Comment by strk** [comment]
I get travis is different from github-ci in that reguard ?
https://github.com/postgis/postgis/pull/54#issuecomment-158306443

My understanding is that "sudo" is not allowed because you're already root (at least on github-ci shared builders).

Actually, now that I'm learning more about dockers it makes sense to be root inside a docker, as it's a jailed root.

**Comment by mloskot** [comment]
@strk  I have no experience with github-ci, in fact, you've just made me aware of it.

**Pull request closed without merging**
