### PR TITLE
ST_ConvexHullAgg

### PR DESCRIPTION
**Pull request by pramsey**
As described in https://trac.osgeo.org/postgis/ticket/3770,
Take in a set of geometry and return convex full of full set.

### CODE REVIEW

**Comment by pramsey** [comment]
☝️ @robe2

**Comment by pramsey** [comment]
OK, ran some tests against this, and the performance is terrible. So the assumptions in the trac ticket
* this might have less memory pressure, yes
* this might be faster, no

**Comment by robe2** [comment]
Should we give up on this as hopeless?  Only real reason for having it is if it could be faster than ST_ConvexHull(ST_Collect(..)).  If it can't then the extra keystrokes is not worth the addition of a new agg.

**Comment by robe2** [comment]
I'm closing this one out as I think we decided it's hopeless

**Pull request closed without merging**
