### PR TITLE
Add libm to LDFLAGS during configure

### PR DESCRIPTION
**Pull request by Algunenano**
So we don't need to add it everywhere

I hope this fixes for https://trac.osgeo.org/postgis/ticket/4532

### CODE REVIEW

**Comment by df7cb** [comment]
That fails here because it's trying to link postgis.so as an executable:
```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
 -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -pie -fno-omit-frame-pointer -fPIC -shared -o postgis-3.so postgis_module.o lwgeom_accum.o lwgeom_spheroid.o lwgeom_og
c.o lwgeom_functions_analytic.o lwgeom_inout.o lwgeom_functions_basic.o lwgeom_btree.o lwgeom_box.o lwgeom_box3d.o lwgeom_geos.o lwgeom_sfcgal.o lwgeom_geos_prepared.o lwgeom_geos_clean.o lwgeo
m_geos_relatematch.o lwgeom_export.o lwgeom_in_gml.o lwgeom_in_kml.o lwgeom_in_geohash.o lwgeom_in_geojson.o lwgeom_in_encoded_polyline.o lwgeom_triggers.o lwgeom_dump.o lwgeom_dumppoints.o lwg
eom_functions_lrs.o lwgeom_functions_temporal.o lwgeom_rectree.o long_xact.o lwgeom_sqlmm.o lwgeom_rtree.o lwgeom_transform.o lwgeom_window.o gserialized_typmod.o gserialized_gist_2d.o gseriali
zed_gist_nd.o gserialized_supportfn.o gserialized_spgist_2d.o gserialized_spgist_3d.o gserialized_spgist_nd.o brin_2d.o brin_nd.o brin_common.o gserialized_estimate.o geography_inout.o geograph
y_btree.o geography_centroid.o geography_measurement.o geography_measurement_trees.o geometry_inout.o postgis_libprotobuf.o vector_tile.pb-c.o geobuf.pb-c.o mvt.o lwgeom_out_mvt.o geobuf.o lwge
om_out_geobuf.o lwgeom_out_geojson.o postgis_legacy.o -L/usr/lib/x86_64-linux-gnu  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -L/usr/lib/llvm-6.0/lib  -L/usr/lib/x86_64-linux-gnu/mit-krb5
 -Wl,--as-needed  ../deps/wagyu/libwagyu.la -lstdc++ ../libpgcommon/libpgcommon.a ../liblwgeom/.libs/liblwgeom.a  -L/usr/lib/x86_64-linux-gnu -lgeos_c -lproj -ljson-c -lprotobuf-c -lxml2 -L/usr
/lib/x86_64-linux-gnu -lSFCGAL -Wl,--exclude-libs,ALL -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -lm -L/usr/lib/x86_64-linux-gnu -lSFCGAL 
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
postgis_module.o: In function `_PG_init':
/srv/projects/postgresql/postgis/postgis/postgis/postgis_module.c:65: undefined reference to `pqsignal'
postgis_module.o: In function `_PG_fini':
/srv/projects/postgresql/postgis/postgis/postgis/postgis_module.c:83: undefined reference to `elog_start'
/srv/projects/postgresql/postgis/postgis/postgis/postgis_module.c:83: undefined reference to `elog_finish'
/srv/projects/postgresql/postgis/postgis/postgis/postgis_module.c:84: undefined reference to `pqsignal'
lwgeom_accum.o: In function `pgis_geometry_accum_transfn':
/srv/projects/postgresql/postgis/postgis/postgis/lwgeom_accum.c:74: undefined reference to `get_fn_expr_argtype'
/srv/projects/postgresql/postgis/postgis/postgis/lwgeom_accum.c:81: undefined reference to `AggCheckCallContext'
... 3000 lines omitted ...
/srv/projects/postgresql/postgis/postgis/libpgcommon/lwgeom_pg.c:127: undefined reference to `TypenameGetTypid'
/srv/projects/postgresql/postgis/postgis/libpgcommon/lwgeom_pg.c:125: undefined reference to `TypenameGetTypid'
/srv/projects/postgresql/postgis/postgis/libpgcommon/lwgeom_pg.c:123: undefined reference to `TypenameGetTypid'
/srv/projects/postgresql/postgis/postgis/libpgcommon/lwgeom_pg.c:121: undefined reference to `TypenameGetTypid'
../libpgcommon/libpgcommon.a(lwgeom_pg.o):/srv/projects/postgresql/postgis/postgis/libpgcommon/lwgeom_pg.c:119: more undefined references to `TypenameGetTypid' follow
collect2: error: ld returned 1 exit status
/usr/lib/postgresql/11/lib/pgxs/src/makefiles/../../src/Makefile.shlib:309: recipe for target 'postgis-3.so' failed
make[3]: *** [postgis-3.so] Error 1
make[3]: Leaving directory '/srv/projects/postgresql/postgis/postgis/postgis'
```

**Comment by Algunenano** [comment]
I'm sorry but I don't understand what you mean. It's passing all the necessary object files, the `-shared` flag and the dynamic libraries so the dependencies are set in the `.so`. What's the issue exactly?

How should the command look like to work in that system? What flags do you think we need to add or remove?

**Comment by df7cb** [comment]
I don't know what's wrong - the patch caused that error, which just looks like it's not trying to build a shared object. I don't know why it's doing that. Removing the patch made it compile again. I don't think my build env was unclean, but if you think it's worth a second try, I can do that.

**Comment by Algunenano** [comment]
AFAIK, all this patch did was adding the extra `-lm` at the end of the command (before `-L/usr/lib/x86_64-linux-gnu -lSFCGAL`) so I don't know how it might have caused that, unless it has somehow polluted other flags during configure.

Since this modifies configure.ac, make sure you run ./autogen.sh before `configure`.

**Comment by Algunenano** [comment]
@df7cb Can you please confirm if this works (or breaks the build) to apply it in RC2?

**Comment by df7cb** [comment]
I tried this patch again on top of the 3.0.0rc1 tarball:
* In Debian sid, the patch works (or rather, doesn't change the behavior)
* In Ubuntu xenial, the build breaks with the patch as said above, and removing the patch makes the build show the expected "undefined reference to symbol 'roundf@@GLIBC_2.2.5'" error

**Pull request closed without merging**
