### PR TITLE
add min/max resampling as options

### PR DESCRIPTION
**Pull request by christianaaronschroeder**
add GDAL MAX and MIN as options for valid GDAL resample algorithms

### CODE REVIEW

**Comment by pramsey** [comment]
Should there be some extra doco to go with this?

**Comment by robe2** [comment]
> Should there be some extra doco to go with this?

Yes there should be in these sections -- https://postgis.net/docs/manual-dev/RT_ST_Resample.html

http://postgis.net/docs/manual-dev/RT_ST_Rescale.html

Which are both in the doc/reference_raster.xml file.

We could make that list a bit more prominent, blends in too easily with the rest of the text.

also  make sure to note a
```
Changed: 3.4.0 max and min resampling options added

```

**Comment by robe2** [comment]
@christianaaronschroeder Just checking if you can make the suggested changes to the doco and then we can accept this.  Also adding a test example for this in https://github.com/postgis/postgis/blob/master/raster/test/regress/rt_gdalwarp.sql would be needed.

**Comment by christianaaronschroeder** [comment]
@robe2 so sorry. can work on test example soon

**Comment by robe2** [comment]
Looks like you got flagged by the dreaded trailing space check.

./raster/rt_core/rt_util.c:113

**Comment by robe2** [comment]
okay now failing on documentation

```
informalequation | informalexample | informalfigure | informaltable | equation | example | figure | table | msgset | procedure | sidebar | qandaset | task | anchor | bridgehead | remark | highlights | abstract | authorblurb | epigraph | indexterm | beginpage)+ , refsection*) | refsection+)), got (title para list para para para para note note para para )
            </refsection>
                         ^
make[1]: *** [Makefile:440: check-unit] Error 4
make[1]: Leaving directory '/src/postgis/doc'
make: *** [GNUmakefile:25: check-unit] Error 1
Error: Process completed with exit code 2.
```
I think it's because of your **list** tag. I don't think there is such a thing in docbook.  Should replace with **itemizedlist** as detailed here - https://tdg.docbook.org/tdg/5.0/itemizedlist.html

I'd also put a **para** tags around it.

Also it looks like you took out a CHANGED notice.  Can you put that back, or was there a reason you took it out.  Multiple CHANGED notices are allowed.

**Comment by robe2** [comment]
@christianaaronschroeder   Just checking if you need help on this.  I can fix up the docs if you are struggling with it.

**Comment by christianaaronschroeder** [comment]
> @christianaaronschroeder Just checking if you need help on this. I can fix up the docs if you are struggling with it.

@robe2 Hi, sorry about the delay. Haven't had time so this went to the backburner. If you could fix up the docs, that would be greatly appreciated!

**Comment by robe2** [comment]
> > @christianaaronschroeder Just checking if you need help on this. I can fix up the docs if you are struggling with it.
> 
> @robe2 Hi, sorry about the delay. Haven't had time so this went to the backburner. If you could fix up the docs, that would be greatly appreciated!

No problem.  I should have committed in a bit.  The doc issue is fixed, but there seems to be an issue with the test  as shown
here - https://woodie.osgeo.org/robe/postgis/build/3/8

I think it's just a typo.  Will let you know if it is more than that.

```
/woodpecker/src/git.osgeo.org/gitea/robe/postgis/raster/test/regress/rt_gdalwarp .. failed (diff expected obtained: /tmp/pgis_reg/test_274_diff)
269s
2400
-----------------------------------------------------------------------------
269s
2401
--- /woodpecker/src/git.osgeo.org/gitea/robe/postgis/raster/test/regress/rt_gdalwarp_expected 2022-12-03 21:27:25.777505129 +0000
269s
2402
+++ /tmp/pgis_reg/test_274_out 2022-12-03 21:32:48.402016547 +0000
269s
2403
@@ -5,8 +5,7 @@
269s
2404
NOTICE: Raster has default geotransform. Adjusting metadata for use of GDAL Warp API
269s
2405
NOTICE: Raster has default geotransform. Adjusting metadata for use of GDAL Warp API
269s
2406
NOTICE: Raster has default geotransform. Adjusting metadata for use of GDAL Warp API
269s
2407
-NOTICE: Values must be provided for both X and Y when specifying the scale. Returning original raster
269s
2408
-NOTICE: Values must be provided for both X and Y when specifying the scale. Returning original raster
269s
2409
+ERROR: syntax error at or near ";" at character 3204
269s
2410
0.0|||||||||||||
269s
2411
0.10|992163|10|10|1|1000.000|-1000.000|0.000|0.000|-500000.000|600000.000|t|t|t
269s
2412
0.11|992163|11|10|1|1000.000|-1000.000|0.000|0.000|-500001.000|600000.000|t|t|t
269s
2413
@@ -23,32 +22,6 @@
269s
2414
0.7|992163|20|20|1|500.000|500.000|0.000|0.000|-500000.000|590000.000|t|t|t
269s
2415
0.8|992163|40|40|1|250.000|250.000|0.000|0.000|-500000.000|590000.000|t|t|t
269s
2416
0.9|992163|40|40|1|250.000|250.000|0.000|0.000|-500000.000|590000.000|t|t|t
269s
2417
-1.0|||||||||||||
269s
2418
-1.1|992163|10|10|1|1000.000|-1000.000|0.000|0.000|-500000.000|600000.000|t|t|t
269s
2419
-1.10|992163|10|11|1|1000.000|-1000.000|0.000|0.000|-500000.000|600009.000|t|t|t
269s
2420
-1.11|992163|11|11|1|1000.000|-1000.000|0.000|0.000|-500100.000|600950.000|t|t|t
269s
2421
-1.12|992163|201|201|1|50.000|50.000|0.000|0.000|-500040.000|589957.000|t|t|t
269s
2422
-1.13|992163|84|84|1|121.000|121.000|0.000|0.000|-500093.000|589875.000|t|t|t
269s
2423
-1.14|992163|201|201|1|50.000|50.000|0.000|0.000|-500040.000|589957.000|t|t|t
269s
2424
-1.15|992163|201|201|1|50.000|50.000|0.000|0.000|-500040.000|589957.000|t|t|t
269s
2425
-1.16|992163|10|10|1|1000.000|-1000.000|3.000|3.000|-500030.000|600000.000|t|t|t
269s
2426
-1.17|992163|10|10|1|1000.000|-1000.000|3.000|3.000|-500030.000|600000.000|t|t|t
269s
2427
-1.18|992163|10|10|1|1000.000|-1000.000|1.000|3.000|-500010.000|600000.000|t|t|t
269s
2428
-1.19|992163|20|20|1|500.000|500.000|3.000|3.000|-500065.000|590065.000|t|t|t
269s
2429
-1.2|992163|20|20|1|500.000|500.000|0.000|0.000|-500000.000|590000.000|t|t|t
269s
2430
-1.20|992163|21|21|1|500.000|500.000|0.000|6.000|-500048.000|590038.000|t|t|t
269s
2431
-1.21|992163|207|101|1|50.000|-100.000|3.000|0.000|-500319.000|600056.000|t|t|t
269s
2432
-1.22|992163|207|101|1|50.000|-100.000|3.000|0.000|-500319.000|600056.000|t|t|t
269s
2433
-1.23|992163|150|150|1|66.667|-66.667|0.000|0.000|-500000.000|600000.000|t|t|t
269s
2434
-1.24|992163|5|5|1|2064.200|-2291.200|0.000|0.000|-500321.000|601456.000|t|t|t
269s
2435
-1.25|||||||||||||
269s
2436
-1.3|992163|10|10|1|1000.000|-1000.000|0.000|0.000|-500000.000|600000.000|t|t|t
269s
2437
-1.4|992163|10|10|1|1000.000|-1000.000|0.000|0.000|-500000.000|600000.000|t|t|t
269s
2438
-1.5|992163|20|20|1|500.000|500.000|0.000|0.000|-500000.000|590000.000|t|t|t
269s
2439
-1.6|992163|40|40|1|250.000|250.000|0.000|0.000|-500000.000|590000.000|t|t|t
269s
2440
-1.7|992163|40|40|1|250.000|250.000|0.000|0.000|-500000.000|590000.000|t|t|t
269s
2441
-1.8|992163|10|10|1|1000.000|-1000.000|0.000|0.000|-500000.000|600000.000|t|t|t
269s
2442
-1.9|992163|11|10|1|1000.000|-1000.000|0.000|0.000|-500001.000|600000.000|t|t|t
269s
2443
2.4|||||||||||||
269s
2444
2.6|||||||||||||
269s
2445
3.1|992163|100|100|1|100.000|100.000|0.000|0.000|-500000.000|590000.000|t|t|t
269s
2446
@@ -57,6 +30,8 @@
269s
2447
3.4|992163|10|10|1|1000.000|-1000.000|0.000|0.000|-500000.000|600000.000|t|t|t
269s
2448
3.5|992163|100|100|1|100.000|100.000|0.000|0.000|-500000.000|590000.000|t|t|t
269s
2449
3.6|992163|67|80|1|150.000|125.000|0.000|0.000|-500000.000|590000.000|t|t|t
269s
2450
+3.7|992163|67|80|1|150.000|125.000|0.000|0.000|-500000.000|590000.000|t|t|t
269s
2451
+3.8|992163|67|80|1|150.000|125.000|0.000|0.000|-500000.000|590000.000|t|t|t
269s
2452
4.1|992163|10|10|1|1000.000|-1000.000|0.000|0.000|-500000.000|600000.000|t|t|t
269s
2453
4.2|992163|10|10|1|1000.000|-1000.000|1.000|1.000|-500010.000|600000.000|t|t|t
269s
2454
4.3|992163|10|10|1|1000.000|-1000.000|0.500|0.000|-500010.000|600000.000|t|t|t
269s
2455
----------------------------------------------------------------------------- 
```

**Pull request closed without merging**
