### PR TITLE
Minor changes to test cases

### PR DESCRIPTION
**Pull request by jimjonesbr**
- Adds missing ST_AsText(geom,5) to input test polygon_14
- Adds ORDER BY to output tests

### CODE REVIEW

**Comment by robe2** [comment]
@jimjonesbr  Last failure is my fault -- that I broke the upgrade.  So don't worry about it. https://cloud.drone.io/postgis/postgis/2726 

I'll commit your work in a bit.

**Comment by jimjonesbr** [comment]
> @jimjonesbr Last failure is my fault -- that I broke the upgrade. So don't worry about it. https://cloud.drone.io/postgis/postgis/2726
> 
> I'll commit your work in a bit.

Okay, thanks for letting me know :) I hope it now fixes the issue on the 32bit architecture.

**Comment by robe2** [comment]
> 

We'll see I committed at 329eab4d00c7be3fb99873ca9de519c574198aa0

Hopefully it will just close this pull request, but maybe it got confused cause I added a bunch of commits on top or it's waiting for regress to complete.

**Comment by jimjonesbr** [comment]
Thanks @robe2

**Pull request closed without merging**
