### PR TITLE
Have travis also run installcheck

### PR DESCRIPTION
**Pull request by strk**
... and expect it to fail due to
https://trac.osgeo.org/postgis/ticket/4486

### CODE REVIEW

**Comment by strk** [comment]
Annoying Travis: /bin/mkdir: cannot create directory '/usr/local/pgsql/share/contrib': Permission denied
@Komzpa what do  you think ? https://travis-ci.org/postgis/postgis/jobs/575300912#L3230

**Comment by Komzpa** [comment]
@strk you have removed sudo. You remove sudo - you deal with ACLs. :)

**Comment by strk** [comment]
I removed sudo because it was prompting me for a password (see previous build).
Since gitlab-ci does correctly run `installcheck` I lost interest in this PR anyway :)

**Comment by strk** [comment]
For the record: https://travis-ci.org/postgis/postgis/jobs/575252011#L3125
```
We trust you have received the usual lecture from the local System

Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.

    #2) Think before you type.

    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified

The command "docker run $ci_env --name pgtest-${TRAVIS_BUILD_NUMBER} pgtest" exited with 1.
```

**Pull request closed without merging**
