### PR TITLE
Reinstate sfcgal functions

### PR DESCRIPTION
**Pull request by lbartoletti**
In version 2.x of PostGIS, there was a mechanism for choosing the backend between
GEOS and SFCGAL for certain operations. When adding the SFCGAL extension, the
backend was removed, and some SFCGAL functions that duplicated GEOS functionality
were also removed. This commit reintroduces these functions but prefixes them
with CG_ to distinguish them from the "classic" GEOS functions using the prefix
ST_.
Often, the 2D functions will produce the same result, sometimes with small
differences due to the algorithms or calculation methods used.

Fixes https://trac.osgeo.org/postgis/ticket/5405

### CODE REVIEW

**Comment by robe2** [comment]
> For the documentation, I added each function in a new sub-folder to make the file `reference_sfcgal.xml` more digestible. It seems to me that we have to add the ENTRY in `postgis.xml`; I couldn't do it in `reference_sfcgal.xml.` In another PR, I will put the functions prefixed with `CG_` instead of `ST_` in the same sub-folder, and I will update and organize the functions in `reference_sfcgal.xml`.

I'd rather we not break each function into a separate file.  It's not like there are that many that reference_sfcgal.xml is that bloated.  It would also break convention, as other extensions and even postgis proper, do not have a separate file for each function.

We could have more than one sfcgal file, if you feel there are distinct themes deserving their own dedicated file.

**Comment by lbartoletti** [comment]
> > For the documentation, I added each function in a new sub-folder to make the file `reference_sfcgal.xml` more digestible. It seems to me that we have to add the ENTRY in `postgis.xml`; I couldn't do it in `reference_sfcgal.xml.` In another PR, I will put the functions prefixed with `CG_` instead of `ST_` in the same sub-folder, and I will update and organize the functions in `reference_sfcgal.xml`.
> 
> I'd rather we not break each function into a separate file. It's not like there are that many that reference_sfcgal.xml is that bloated. It would also break convention, as other extensions and even postgis proper, do not have a separate file for each function.
> 
> We could have more than one sfcgal file, if you feel there are distinct themes deserving their own dedicated file.

OK, done in [a6dac83](https://github.com/postgis/postgis/pull/760/commits/a6dac8382bdcd401f15620d03c1e88ef61cc40d6)

**Comment by robe2** [comment]
@lbartoletti  Now that you have commit rights, feel free to commit this yourself. Let me know if you have any questions.

**Review by robe2 — APPROVED** [review]
All looks good to me

**Comment by lbartoletti** [comment]
> @lbartoletti Now that you have commit rights, feel free to commit this yourself. Let me know if you have any questions.

Yes, I didn't see anything in the documentation. But, is it safe to merge on github, or should I push my commits to gitea?

I opened here, to check the Cirrus CI at the same time. I've seen other PRs integrated from Github, but I'm intrigued by this sentence in the documentation:
_Changes committed to mirror sites will be overwritten the next time a change is synchronized from OSGeo._

**Comment by lbartoletti** [comment]
Pushed in https://git.osgeo.org/gitea/postgis/postgis/commit/3b516cba062739f0f7992827d57217152948d155

**Pull request closed without merging**
