### PR TITLE
ccache to make compilation faster

### PR DESCRIPTION
**Pull request by Komzpa**

### CODE REVIEW

**Comment by dbaston** [comment]
Publishing a Docker image for our build environment would also make a big improvement in the Travis build times. One of many things I finished but then lost...

**Comment by strk** [comment]
@dbaston like https://git.osgeo.org/gogs/postgis/postgis-docker which is already used by drone agents reporting to https://drone.osgeo.org/postgis/postgis builds triggered by pushing to https://git.osgeo.org/gogs/postgis/postgis ?

@kashif pushed with:
r15878 = 1c9b9a7ce441c834d3a2f9e9468e367d1c56f349 (refs/remotes/svn/trunk)
r15879 = bb2a055fabfdfdadf2f77e4297241d80617f370f (refs/remotes/svn/trunk)

**Comment by dbaston** [comment]
@strk yes, along those lines, but for Travis. That particular image probably isn't a good fit for testing community contributions, though.

**Comment by strk** [comment]
@dbaston that docker repository is open for building multiple images,
just wanted to give you a place to build whatever you think is needed
for testing community contributions. The more images we have, the more
systems/environments we'll be able to have bots test. I don't like,
generally, the trend of biodiversity reduction introduced by travis 
and docker :)

**Pull request closed without merging**
