### PR TITLE
Move travis config under ci/ dir

### PR DESCRIPTION
**Pull request by strk**

### CODE REVIEW

**Comment by strk** [comment]
@robe is using a symlink a no-go for windows ?
(actually, do we care at all about windows when it comes to travis config ?)

This commit makes .travis.yml a symlink to ci/travis/config.yml, basically

**Comment by strk** [comment]
actually, I wonder if SVN supports symlinks (probably not?)

**Comment by pramsey** [comment]
Close this, @strk ?

**Comment by pramsey** [comment]
This seems to have been done in SVN, closing.

**Pull request closed without merging**
