### PR TITLE
test_rect_tree_contains_point: Fix memory leaks

### PR DESCRIPTION
**Pull request by Algunenano**

### CODE REVIEW

**Comment by Algunenano** [comment]
Trac issue: https://trac.osgeo.org/postgis/ticket/4026 I'll try to push this fix myself.

**Comment by Komzpa** [comment]
@Algunenano do you need help with svn assimilation? :)

**Comment by Algunenano** [comment]
I think I just need some time to sit down and check svn commands and how to apply the patch from git into svn. I'll try to merge this later

**Comment by Komzpa** [comment]
```
svn co https://svn.osgeo.org/postgis/
cd postgis/trunk/
wget -O - https://patch-diff.githubusercontent.com/raw/postgis/postgis/pull/216.diff | patch -p1
svn status # check everything ok, svn add / svn rm to rm
svn ci
--<edit commit message, template:>
[name of PR]

[if patch is not your, Patch by [user name]]

Closes #[trac_ticket_number]
Closes https://github.com/postgis/postgis/pull/[PR_NUM]
--
#authenticate
#wait
#check bots
```

**Comment by Algunenano** [comment]
:raised_hands: It works! Thanks @Komzpa

**Pull request closed without merging**
